# Individual Income Tax Overview, Dependents, and Filing Status

**Comprehensive Problems**

McGraw Hill's Taxation of Individuals and Business Entities 2025

Spilker, Ayers, Lewis, Weaver, Barrick, Robinson, Worsham

In [ ]:
import os
import sys

mod_path = os.path.abspath(os.path.join("../.."))
if mod_path not in sys.path:
    sys.path.append(mod_path)

from income_tax import OrdinaryIncomeTax, IncomeTaxSummary

##### **Demarco and Janine Jackson have been married for 20 years and have four children who qualify as their dependents (Damarcus, Jasmine, Michael, and Candice). The Jacksons file a joint tax return. The couple received salary income of 105,000 and qualified business income of 10,000 from an investment in a partnership, and they sold their home this year. They initially purchased the home three years ago for 200,000, and they sold it for 250,000. The gain on the sale qualified for the exclusion from the sale of a principal residence. The Jacksons incurred 16,500 of itemized deductions, and they had 4,000 withheld from their paychecks for federal taxes. They are also allowed to claim a child tax credit for each of their children. However, because Candice is 18 years of age at year-end, the Jacksons may claim a child tax credit for other qualifying dependents for Candice.**

In [2]:
# Data Gathering
# Tax year: 2025

age = 45                                                        # N/A 
status = "MFJ"                                                  # Filing sttus
salaries = 105000                                               # Combined salaries
qualified_business_income = 10000                               # Partnership
gross_income = salaries + qualified_business_income
non_taxable_capital_gains = 250000 - 200000
total_income = gross_income + non_taxable_capital_gains
adjustments = 0                                                 # N/A
itemized_deduction = 16500                                      # MFJ 2025 - 31,500
qbi_deduction = qualified_business_income * .20                 # Assuming no phaseout
capital_gains = 0                                               # N/A
capital_gains_tax = 0                                           # N/A 
child_tax_credit = -2000 * 3                                    # under 17 dependents       
credit_for_other_dependent = -500                               # Candice
total_credits = child_tax_credit + credit_for_other_dependent
withholdings = -4000                                            # Prepayments

income_tax = OrdinaryIncomeTax(status, age, gross_income, adjustments, itemized_deduction, qbi_deduction).calculate_tax()

- **a) What is the Jacksons’ taxable income, and what is their tax liability or (refund)?**

In [3]:
summary = IncomeTaxSummary(
    income_tax["gross_income"], 
    income_tax["adjustments"],
    income_tax["deduction"],
    income_tax["qbi_deduction"],
    capital_gains,
    income_tax["ordinary_tax"],
    capital_gains_tax,
    total_credits,
    withholdings)

it_summary = summary.income_tax_summary()
tax_due_refund = income_tax["ordinary_tax"] + total_credits + withholdings
results = "Tax due" if tax_due_refund >= 0 else "Tax refund"
print(f"{results}: ${tax_due_refund:,.0f} as shown in the summary below.")
display(HTML(it_summary.to_html(index=False)))

Tax refund: $-1,197 as shown in the summary below.

- **b) Complete the Jacksons’ Form 1040, pages 1, 2, and Schedule 1 (use the most recent form available).**
    - **Tax Return:** [Demarco and Janine's Tax Returns](Comprehensive_Problems_Tax_Returns/Demarco_and_Janine_Tax_Return_2025-.pdf)

- **c) What would their taxable income be if their itemized deductions totaled 34,000 instead of 16,500?**

In [4]:
itemized_deduction = 34000

income_tax = OrdinaryIncomeTax(status, age, gross_income, adjustments, itemized_deduction, qbi_deduction).calculate_tax()
summary = IncomeTaxSummary(
    income_tax["gross_income"], 
    income_tax["adjustments"],
    income_tax["deduction"],
    income_tax["qbi_deduction"],
    capital_gains,
    income_tax["ordinary_tax"],
    capital_gains_tax,
    total_credits,
    withholdings)

it_summary = summary.income_tax_summary()
tax_due_refund = income_tax["ordinary_tax"] + total_credits + withholdings
results = "Tax due" if tax_due_refund >= 0 else "Tax refund"
print(f"{results}: ${tax_due_refund:,.0f} as shown in the summary below.")
display(HTML(it_summary.to_html(index=False)))

Tax refund: $-1,497 as shown in the summary below.

- **d) What would their taxable income be if they had 0 itemized deductions and 6,000 of for AGI deductions?**

In [6]:
itemized_deduction = 0
adjustments = 6000

income_tax = OrdinaryIncomeTax(status, age, gross_income, adjustments, itemized_deduction, qbi_deduction).calculate_tax()
summary = IncomeTaxSummary(
    income_tax["gross_income"], 
    income_tax["adjustments"],
    income_tax["deduction"],
    income_tax["qbi_deduction"],
    capital_gains,
    income_tax["ordinary_tax"],
    capital_gains_tax,
    total_credits,
    withholdings)

it_summary = summary.income_tax_summary()
tax_due_refund = income_tax["ordinary_tax"] + total_credits + withholdings
results = "Tax due" if tax_due_refund >= 0 else "Tax refund"
print(f"{results}: ${tax_due_refund:,.0f} as shown in the summary below.")
display(HTML(it_summary.to_html(index=False)))

Tax refund: $-1,917 as shown in the summary below.

- **e) Assume the original facts but now suppose the Jacksons also incurred a loss of 5,000 on the sale of some of their investment assets. What effect does the 5,000 loss have on their taxable income?**

In [7]:
investment_loss = 5000
capital_loss = min(investment_loss, 3000)
gross_income -= capital_loss
itemized_deduction = 16500
adjustments = 0

income_tax = OrdinaryIncomeTax(status, age, gross_income, adjustments, itemized_deduction, qbi_deduction).calculate_tax()
summary = IncomeTaxSummary(
    income_tax["gross_income"], 
    income_tax["adjustments"],
    income_tax["deduction"],
    income_tax["qbi_deduction"],
    capital_gains,
    income_tax["ordinary_tax"],
    capital_gains_tax,
    total_credits,
    withholdings)

it_summary = summary.income_tax_summary()
tax_due_refund = income_tax["ordinary_tax"] + total_credits + withholdings
results = "Tax due" if tax_due_refund >= 0 else "Tax refund"
print(f"{results}: ${tax_due_refund:,.0f} as shown in the summary below.")
display(HTML(it_summary.to_html(index=False)))

Tax refund: $-1,557 as shown in the summary below.

- **f) Assume the original facts but now suppose the Jacksons own investments that appreciated by 10,000 during the year. The Jacksons believe the investments will continue to appreciate, so they did not sell the investments during this year. What is the Jacksons’ taxable income?**
    - **Answer:** Their taxable income will remain the same (81,500).  This is an example of capital appreciation, a non-taxable event, when the asset raises in value but remains unsold.  If, on the other hand, the Jackson would have sold the asset the they would recognized a short or long-term capital gain depending on the character of the gain.